# Generated by Django 4.1.2 on 2022-10-09 17:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=254, null=True)),
                ('name_trans', models.CharField(max_length=254, null=True)),
                ('daily', models.IntegerField()),
                ('positiv', models.IntegerField()),
                ('negativ', models.IntegerField()),
                ('propos', models.IntegerField()),
                ('shop', models.CharField(max_length=254, null=True)),
                ('leisure', models.CharField(max_length=254, null=True)),
                ('amenity', models.CharField(max_length=254, null=True)),
                ('public_tra', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['name_trans'],
            },
        ),
    ]
